before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq firebird2.5-superclassic firebird2.5-dev
  - sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i /etc/default/firebird2.5
  - cat /etc/default/firebird2.5 | grep ENABLE_FIREBIRD_SERVER
  - sudo service firebird2.5-superclassic start
services:
  - postgresql
before_script:
  - psql -c 'create database emap_test;' -U postgres
env:
  global:
    - EMAP_DBS="POSTGRES,FIREBIRD"
    - EMAP_DB_POSTGRES_USER=postgres
    - EMAP_DB_POSTGRES_PASSWORD=
    - EMAP_DB_POSTGRES_URL=jdbc:postgresql:emap_test
    - EMAP_DB_POSTGRES_NAME=Postgres
    - EMAP_DB_POSTGRES_DRIVER=org.postgresql.Driver
    - EMAP_DB_FIREBIRD_USER=TODO
    - EMAP_DB_FIREBIRD_PASSWORD=
    - EMAP_DB_FIREBIRD_DRIVER=org.firebirdsql.jdbc.FBDriver
language: java
cache:
  directories:
  - $HOME/.m2
script: cd releng && mvn verify
after_failure:
  - cat ../test/test.junit/target/surefire-reports/*.txt

