services:
  - postgresql
before_script:
  - psql -c 'create database emap_test;' -U postgres
env:
  global:
    - EMAP_DBS="POSTGRES,FIREBIRD"
    - EMAP_DB_POSTGRES_USER=postgres
    - EMAP_DB_POSTGRES_PASSWORD=
    - EMAP_DB_POSTGRES_URL=jdbc:postgresql:emap_test
    - EMAP_DB_POSTGRES_NAME=Postgres
    - EMAP_DB_POSTGRES_DRIVER=org.postgresql.Driver
    - EMAP_DB_FIREBIRD_USER=TODO
    - EMAP_DB_FIREBIRD_PASSWORD=
    - EMAP_DB_FIREBIRD_DRIVER=org.firebirdsql.jdbc.FBDriver
language: java
cache:
  directories:
  - $HOME/.m2
script: cd releng && mvn verify
after_failure:
  - cat ../test/test.junit/target/surefire-reports/*.txt

